# Generated by Django 5.0.1 on 2024-01-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GolfCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "hole_count",
                    models.CharField(
                        choices=[("9", "9 Holes"), ("18", "18 Holes")],
                        default="9",
                        max_length=64,
                    ),
                ),
                ("tee_time_link", models.URLField(blank=True)),
                ("website_link", models.URLField(blank=True)),
                ("city", models.CharField(blank=True, max_length=128)),
                ("state", models.CharField(blank=True, max_length=128)),
                ("zip_code", models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
