# Generated by Django 5.0.1 on 2024-01-30 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_playergamelink_game_players"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoleScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_par", models.IntegerField(default=0)),
                ("score", models.IntegerField(default=0)),
                (
                    "game_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.playergamelink",
                    ),
                ),
                (
                    "hole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.hole"
                    ),
                ),
            ],
        ),
    ]
